### ISSUE TITLE
@interface instead of plugin?

### ISSUE THREAD

**Issue by Ribosom** [Gerrit0/typedoc-plugin-zod#1]
I have a question:

I used your plugin (Thank you for your plugin), but now I am asking myself if the plugin does the same as `@interface`. https://typedoc.org/tags/interface/ 

Or has the plugin extra features, I have overlooked? Are there points, why you would recommend using the plugin over `@interface`?

```ts
/**
 * @interface
 */
export type MyType = z.infer<typeof MySchema>;
```

**Comment by Gerrit0** [comment]
There's one other instance in which this plugin is useful -- if you have exported variables which reference the type, this plugin will replace the type so that it references your created interface: https://gerritbirkeland.com/typedoc-plugin-zod/variables/abc-1.html

You're absolutely right that `@interface` replaces most of the use case for this plugin though, I don't think it existed when I created this plugin... timelines get fuzzy for me.

**Comment by Ribosom** [comment]
Thanks for the answer! Ok, I understand replacing the types in exported variables can be useful.
